Fixed method issue (app.photoBrowser.create)
Method: app.photoBrowser.create.
The method "create" of "photoBrowser" was removed because it doesn't exist anymore.
Error message: Uncaught TypeError: app.photoBrowser.create is not a function.

To create a new instance of "PhotoBrowser", this can be used:
let photoBrowser = this.app.photoBrowser({params});